export * from './AnimalDetailPage';
export * from './AnimalesPage';
export * from './DescarteDetailPage';
export * from './DescartePage';
export * from './FincasPage';
export * from './HomePage';
export * from './LoginPage';
export * from './NotFound';
export * from './PesajeDetailPage';
export * from './PesajePage';
export * from './ProduccionDetailPage';
export * from './ProduccionPage';
export * from './RegisterPage';
export * from './ReproduccionDetailPage';
export * from './ReproduccionPage';
export * from "./PerfilPage"